// AUTO-GENERATED by scripts/build-office.mjs — do not edit by hand.
// A prayable Liturgy of the Hours from public-domain texts (Douay–Rheims psalms
// and canticles, Neale's hymn translations, and the traditional ordinary). Not
// the licensed ICEL psalter.

export type OfficePartType = "versicle" | "hymn" | "psalm" | "canticle" | "reading" | "responsory" | "intercession" | "prayer";

export interface OfficePart {
  type: OfficePartType;
  label?: string;
  sub?: string;
  ref?: string;
  antiphon?: string;
  text: string;
}

export const OFFICE: Record<string, OfficePart[]> = {
  "Office of Readings": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "O Trinity of blessed Light,\nO Unity of princely might,\nThe fiery sun now goes his way;\nShed thou within our hearts thy ray.\nTo thee our morning song of praise,\nTo thee our evening prayer we raise;\nThy glory suppliant we adore\nFor ever and for evermore.\nAll laud to God the Father be,\nAll praise, eternal Son, to thee,\nAll glory, as is ever meet,\nTo God the Holy Paraclete. Amen."
    },
    {
      "type": "psalm",
      "label": "Invitatory · Psalm 95",
      "ref": "Psalm 95",
      "antiphon": "Come, let us worship the Lord, the great King above all gods.",
      "text": "Come let us praise the Lord with joy: let us joyfully sing to God our saviour. Let us come before his presence with thanksgiving; and make a joyful noise to him with psalms. For the Lord is a great God, and a great King above all gods. For in his hand are all the ends of the earth: and the heights of the mountains are his. For the sea is his, and he made it: and his hands formed the dry land. Come let us adore and fall down: and weep before the Lord that made us. For he is the Lord our God: and we are the people of his pasture and the sheep of his hand."
    },
    {
      "type": "psalm",
      "label": "Psalm 1",
      "ref": "Psalm 1",
      "antiphon": "Blessed is the man whose delight is in the law of the Lord.",
      "text": "Blessed is the man who hath not walked in the counsel of the ungodly, nor stood in the way of sinners, nor sat in the chair of pestilence. But his will is in the law of the Lord, and on his law he shall meditate day and night. And he shall be like a tree which is planted near the running waters, which shall bring forth its fruit, in due season. And his leaf shall not fall off: and all whosoever he shall do shall prosper. Not so the wicked, not so: but like the dust, which the wind driveth from the face of the earth. Therefore the wicked shall not rise again in judgment: nor sinners in the council of the just. For the Lord knoweth the way of the just: and the way of the wicked shall perish."
    },
    {
      "type": "psalm",
      "label": "Psalm 103",
      "ref": "Psalm 103 · 1–5",
      "antiphon": "Bless the Lord, O my soul, and forget not all his benefits.",
      "text": "For David himself. Bless the Lord, O my soul: and let all that is within me bless his holy name. Bless the Lord, O my soul, and never forget all he hath done for thee. Who forgiveth all thy iniquities: who healeth all thy diseases. Who redeemeth thy life from destruction: who crowneth thee with mercy and compassion. Who satisfieth thy desire with good things: thy youth shall be renewed like the eagle's."
    },
    {
      "type": "reading",
      "label": "First Reading",
      "ref": "Romans 8 · 28–32",
      "text": "We know that to them that love God all things work together unto good, to such as, according to his purpose, are called to be saints. For whom he foreknew, he also predestinated to be made conformable to the image of his Son, that he might be the firstborn amongst many brethren. What shall we then say to these things? If God be for us, who is against us? He that spared not even his own Son, but delivered him up for us all, how hath he not also, with him, given us all things?"
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "If God be for us, who is against us? In him who loved us we are more than conquerors."
    },
    {
      "type": "reading",
      "label": "Second Reading",
      "ref": "From the Confessions of Saint Augustine",
      "text": "Great art thou, O Lord, and greatly to be praised; great is thy power, and of thy wisdom there is no end. And man, being a part of thy creation, desires to praise thee. Thou awakest us to delight in thy praise; for thou madest us for thyself, and our heart is restless, until it rest in thee. Grant me, Lord, to know and understand which is first, to call on thee, or to praise thee; and, again, to know thee, or to call on thee."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Thou madest us for thyself, O Lord, and our heart is restless until it rest in thee."
    },
    {
      "type": "canticle",
      "label": "Te Deum",
      "sub": "A Hymn of Praise",
      "text": "We praise thee, O God: we acknowledge thee to be the Lord. All the earth doth worship thee, the Father everlasting. To thee all Angels cry aloud, the Heavens and all the Powers therein. To thee Cherubim and Seraphim continually do cry: Holy, Holy, Holy, Lord God of Sabaoth; Heaven and earth are full of the majesty of thy glory. The glorious company of the Apostles praise thee. The goodly fellowship of the Prophets praise thee. The noble army of Martyrs praise thee. The holy Church throughout all the world doth acknowledge thee: the Father, of an infinite majesty; thine adorable, true, and only Son; also the Holy Ghost, the Comforter. Thou art the King of Glory, O Christ. Thou art the everlasting Son of the Father. When thou tookest upon thee to deliver man, thou didst not abhor the Virgin's womb. When thou hadst overcome the sharpness of death, thou didst open the kingdom of heaven to all believers. We therefore pray thee, help thy servants, whom thou hast redeemed with thy precious blood. O Lord, save thy people, and bless thine heritage. Govern them, and lift them up for ever. Day by day we magnify thee; and we worship thy name, ever world without end. O Lord, in thee have I trusted: let me never be confounded."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O God, who hast taught the hearts of thy faithful people by sending to them the light of thy Holy Spirit: grant us by the same Spirit to have a right judgment in all things, and evermore to rejoice in his holy comfort. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Lauds": [
    {
      "type": "versicle",
      "text": "O Lord, open thou my lips, and my mouth shall declare thy praise."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "Now that the daylight fills the sky,\nWe lift our hearts to God on high,\nThat he, in all we do or say,\nWould keep us free from harm to-day:\nMay he restrain our tongues from strife,\nAnd shield from anger's din our life,\nAnd guard with watchful care our eyes\nFrom earth's absorbing vanities.\nAll laud to God the Father be,\nAll praise, eternal Son, to thee,\nAll glory, as is ever meet,\nTo God the Holy Paraclete. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 63",
      "ref": "Psalm 63 · 1–8",
      "antiphon": "O God, my God, to thee do I watch at the break of day.",
      "text": "A psalm of David when he was in the desert of Edom. O God, my God, to thee do I watch at break of day. For thee my soul hath thirsted; for thee my flesh, O how many ways! In a desert land, and where there is no way, and no water: so in the sanctuary have I come before thee, to see thy power and thy glory. For thy mercy is better than lives: thee my lips shall praise. Thus will I bless thee all my life long: and in thy name I will lift up my hands. Let my soul be filled as with marrow and fatness: and my mouth shall praise thee with joyful lips. If I have remembered thee upon my bed, I will meditate on thee in the morning: because thou hast been my helper. And I will rejoice under the covert of thy wings:"
    },
    {
      "type": "psalm",
      "label": "Psalm 100",
      "ref": "Psalm 100",
      "antiphon": "Serve the Lord with gladness; come before him with joyful song.",
      "text": "Sing joyfully to God, all the earth: serve ye the Lord with gladness. Come in before his presence with exceeding great joy. Know ye that the Lord he is God: he made us, and not we ourselves. We are his people and the sheep of his pasture. Go ye into his gates with praise, into his courts with hymns: and give glory to him. Praise ye his name: for the Lord is sweet, his mercy endureth for ever, and his truth to generation and generation."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "Romans 13 · 12",
      "text": "The night is passed, and the day is at hand. Let us therefore cast off the works of darkness, and put on the armour of light."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "I will bless the Lord at all times; his praise shall be ever in my mouth."
    },
    {
      "type": "canticle",
      "label": "The Benedictus",
      "sub": "Canticle of Zechariah",
      "ref": "Luke 1 · 68–79",
      "antiphon": "Blessed be the Lord, the God of Israel, for he hath visited and wrought the redemption of his people.",
      "text": "Blessed be the Lord God of Israel; because he hath visited and wrought the redemption of his people: And hath raised up an horn of salvation to us, in the house of David his servant: As he spoke by the mouth of his holy prophets, who are from the beginning: Salvation from our enemies, and from the hand of all that hate us: To perform mercy to our fathers, and to remember his holy testament, The oath, which he swore to Abraham our father, that he would grant to us, That being delivered from the hand of our enemies, we may serve him without fear, In holiness and justice before him, all our days. And thou, child, shalt be called the prophet of the Highest: for thou shalt go before the face of the Lord to prepare his ways: To give knowledge of salvation to his people, unto the remission of their sins: Through the bowels of the mercy of our God, in which the Orient from on high hath visited us: To enlighten them that sit in darkness, and in the shadow of death: to direct our feet into the way of peace."
    },
    {
      "type": "intercession",
      "label": "Intercessions",
      "text": "Blessed be Christ, who brings us to the light of a new day; with hearts made glad let us call upon him: Lord, guide our hearts and hands this day.\nFor your holy Church throughout the world, that you keep her in your truth and peace.\nYou have brought us safely to this morning: let us walk this day without sin.\nAll that we are and all that we do, let it give you glory.\nBe near to the suffering, the lonely, and the dying, and bring the wanderer home.\nLord, guide our hearts and hands this day."
    },
    {
      "type": "prayer",
      "label": "The Lord's Prayer",
      "text": "Our Father, who art in heaven, hallowed be thy name; thy kingdom come, thy will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "Almighty God, who hast brought us to the beginning of this day: defend us in the same by thy mighty power, that this day we may fall into no sin, but that all our doings may be ordered by thy governance, to do always that which is righteous in thy sight. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Terce": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "Come, Holy Ghost, who ever One\nReignest with Father and with Son,\nIt is the hour, our souls possess\nWith thy full flood of holiness.\nLet flesh and heart and lips and mind\nSound forth our witness to mankind;\nAnd love light up our mortal frame,\nTill others catch the living flame.\nAlmighty Father, hear our cry\nThrough Jesus Christ our Lord most high,\nWho with the Holy Ghost and thee\nDoth live and reign eternally. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 67",
      "ref": "Psalm 67",
      "antiphon": "May God have mercy on us, and bless us.",
      "text": "May God have mercy on us, and bless us: may he cause the light of his countenance to shine upon us, and may he have mercy on us. That we may know thy way upon earth: thy salvation in all nations. Let people confess to thee, O God: let all people give praise to thee. Let the nations be glad and rejoice: for thou judgest the people with justice, and directest the nations upon earth. Let the people, O God, confess to thee: let all the people give praise to thee: the earth hath yielded her fruit. May God, our God bless us,"
    },
    {
      "type": "psalm",
      "label": "Psalm 8",
      "ref": "Psalm 8",
      "antiphon": "O Lord, our Lord, how admirable is thy name in all the earth!",
      "text": "O Lord our Lord, how admirable is thy name in the whole earth! For thy magnificence is elevated above the heavens. Out of the mouth of infants and of sucklings thou hast perfected praise, because of thy enemies, that thou mayst destroy the enemy and the avenger. For I will behold thy heavens, the works of thy fingers: the moon and the stars which thou hast founded. What is man that thou art mindful of him? or the son of man that thou visitest hi? Thou hast made him a little less than the angels, thou hast crowned him with glory and honour: and hast set him over the works of thy hands. Thou hast subjected all things under his feet, all sheep and oxen: moreover the beasts also of the fields. The birds of the air, and the fishes of the sea, that pass through the paths of the sea."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "Acts 2 · 4",
      "text": "And they were all filled with the Holy Spirit, and they began to speak the wonderful works of God."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Come, Holy Spirit, fill the hearts of thy faithful, and kindle in them the fire of thy love."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O Lord, pour forth thy Spirit upon us at this third hour, as thou didst pour him upon the apostles in tongues of fire; that we, made fervent in thy love, may confess thee before all the world. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Sext": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "O God of truth, O Lord of might,\nWho orderest time and change aright,\nAnd send'st the early morning ray,\nAnd light'st the glow of perfect day:\nExtinguish thou each sinful fire,\nAnd banish every ill desire;\nAnd while thou keep'st the body whole,\nShed forth thy peace upon the soul.\nAlmighty Father, hear our cry\nThrough Jesus Christ our Lord most high,\nWho with the Holy Ghost and thee\nDoth live and reign eternally. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 121",
      "ref": "Psalm 121",
      "antiphon": "My help is from the Lord, who made heaven and earth.",
      "text": "I have lifted up my eyes to the mountains, from whence help shall come to me. My help is from the Lord, who made heaven and earth. May he not suffer thy foot to be moved: neither let him slumber that keepeth thee. Behold he shall neither slumber nor sleep, that keepeth Israel. The Lord is thy keeper, the Lord is thy protection upon thy right hand. The sun shall not burn thee by day: nor the moon by night. The Lord keepeth thee from all evil: may the Lord keep thy soul. May the Lord keep thy going in and thy going out; from henceforth now and for ever."
    },
    {
      "type": "psalm",
      "label": "Psalm 122",
      "ref": "Psalm 122",
      "antiphon": "I rejoiced when they said to me: Let us go to the house of the Lord.",
      "text": "I rejoiced at the things that were said to me: We shall go into the house of the Lord. Our feet were standing in thy courts, O Jerusalem. Jerusalem, which is built as a city, which is compact together. For thither did the tribes go up, the tribes of the Lord: the testimony of Israel, to praise the name of the Lord. Because their seats have sat in judgment, seats upon the house of David."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "2 Corinthians 6 · 2",
      "text": "Behold, now is the acceptable time; behold, now is the day of salvation."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "The Lord is my light and my salvation; whom shall I fear?"
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O God, who at the sixth hour didst stretch out thine arms upon the Cross for the salvation of the world: kindle in us at this midday the fire of thy charity, that all our works may be pleasing unto thee. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "None": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "O God, unchangeable and true,\nOf all the Light and Life the source,\nThe day with smiling beams renew,\nAnd lead it through its destined course:\nAnd grant that when the world is dim,\nAnd life's last hour is drawing nigh,\nWe, gazing on thy light, may pass\nBeyond the grave, and never die.\nAlmighty Father, hear our cry\nThrough Jesus Christ our Lord most high,\nWho with the Holy Ghost and thee\nDoth live and reign eternally. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 125",
      "ref": "Psalm 125",
      "antiphon": "They that trust in the Lord shall be as Mount Sion, which cannot be moved.",
      "text": "They that trust in the Lord shall be as mount Sion: he shall not be moved for ever that dwelleth in Jerusalem. Mountains are round about it: so the Lord is round about his people from henceforth now and for ever. For the Lord will not leave the rod of sinners upon the lot of the just: that the just may not stretch forth their hands to iniquity. Do good, O Lord, to those that are good, and to the upright of heart. But such as turn aside into bonds, the Lord shall lead out with the workers of iniquity: peace upon Israel."
    },
    {
      "type": "psalm",
      "label": "Psalm 130",
      "ref": "Psalm 130 · De Profundis",
      "antiphon": "Out of the depths I have cried to thee, O Lord.",
      "text": "Out of the depths I have cried to thee, O Lord: Lord, hear my voice. Let thy ears be attentive to the voice of my supplication. If thou, O Lord, wilt mark iniquities: Lord, who shall stand it. For with thee there is merciful forgiveness: and by reason of thy law, I have waited for thee, O Lord. My soul hath relied on his word: my soul hath hoped in the Lord. From the morning watch even until night, let Israel hope in the Lord. Because with the Lord there is mercy: and with him plentiful redemption. And he shall redeem Israel from all his iniquities."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "Colossians 3 · 17",
      "text": "All whatsoever you do in word or in work, do all in the name of the Lord Jesus Christ, giving thanks to God and the Father by him."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "My soul yearns and pines for the courts of the Lord."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O God, who at the ninth hour didst will that thy Son should taste death for us all: grant that, as the day declines, our hearts may turn ever more wholly unto thee, who livest and reignest, world without end. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Vespers": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "O blest Creator of the light,\nWho mak'st the day with radiance bright,\nAnd o'er the forming world didst call\nThe light from chaos first of all:\nWhose wisdom joined in meet array\nThe morn and eve, and named them Day:\nNight comes with all its darkling fears;\nRegard thy people's prayers and tears.\nAll-holy Father, hear our cry\nThrough Jesus Christ our Lord most high,\nWho with the Holy Ghost and thee\nDoth live and reign eternally. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 113",
      "ref": "Psalm 113",
      "antiphon": "Praise the Lord, ye servants of the Lord; blessed be the name of the Lord.",
      "text": "Praise the Lord, ye children: praise ye the name of the Lord. Blessed be the name of the Lord, from henceforth now and for ever. From the rising of the sun unto the going down of the same, the name of the Lord is worthy of praise. The Lord is high above all nations; and his glory above the heavens. Who is as the Lord our God, who dwelleth on high: and looketh down on the low things in heaven and in earth? Raising up the needy from the earth, and lifting up the poor out of the dunghill:: That he may place him with princes, with the princes of his people. Who maketh a barren woman to dwell in a house, the joyful mother of children."
    },
    {
      "type": "psalm",
      "label": "Psalm 117",
      "ref": "Psalm 117",
      "antiphon": "O praise the Lord, all ye nations; for his mercy is confirmed upon us.",
      "text": "O praise the Lord, all ye nations: praise him, all ye people. For his mercy is confirmed upon us: and the truth of the Lord remaineth for ever."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "2 Corinthians 1 · 3–4",
      "text": "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort, who comforteth us in all our tribulation."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Let my prayer come like incense before thee, the lifting up of my hands like the evening sacrifice."
    },
    {
      "type": "canticle",
      "label": "The Magnificat",
      "sub": "Canticle of Mary",
      "ref": "Luke 1 · 46–55",
      "antiphon": "My soul doth magnify the Lord, and my spirit hath rejoiced in God my Saviour.",
      "text": "And Mary said: My soul doth magnify the Lord. And my spirit hath rejoiced in God my Saviour. Because he hath regarded the humility of his handmaid; for behold from henceforth all generations shall call me blessed. Because he that is mighty, hath done great things to me; and holy is his name. And his mercy is from generation unto generations, to them that fear him. He hath shewed might in his arm: he hath scattered the proud in the conceit of their heart. He hath put down the mighty from their seat, and hath exalted the humble. He hath filled the hungry with good things; and the rich he hath sent empty away. He hath received Israel his servant, being mindful of his mercy: As he spoke to our fathers, to Abraham and to his seed for ever."
    },
    {
      "type": "intercession",
      "label": "Intercessions",
      "text": "Let us give thanks to Christ, the unfading Light, and humbly pray: Lord, hear us, and have mercy.\nFor your holy Church, that you gather and keep her in your peace.\nFor all who govern the nations, that they serve the common good with justice.\nFor the sick, the sorrowing, and the dying, that you comfort and heal them.\nFor ourselves, that the evening of our lives may be without reproach.\nFor all the faithful departed, that you grant them light and rest.\nLord, hear us, and have mercy."
    },
    {
      "type": "prayer",
      "label": "The Lord's Prayer",
      "text": "Our Father, who art in heaven, hallowed be thy name; thy kingdom come, thy will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "Lighten our darkness, we beseech thee, O Lord; and by thy great mercy defend us from all perils and dangers of this night. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Compline": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "hymn",
      "label": "Hymn",
      "text": "Before the ending of the day,\nCreator of the world, we pray\nThat with thy wonted favour thou\nWouldst be our guard and keeper now.\nFrom all ill dreams defend our eyes,\nFrom nightly fears and fantasies;\nTread under foot our ghostly foe,\nThat no pollution we may know.\nO Father, that we ask be done,\nThrough Jesus Christ thine only Son,\nWho, with the Holy Ghost and thee,\nDoth live and reign eternally. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 4",
      "ref": "Psalm 4",
      "antiphon": "Have mercy on me, O Lord, and hear my prayer.",
      "text": "When I called upon him, the God of my justice heard me: when I was in distress, thou hast enlarged me. Have mercy on me: and hear my prayer. O ye sons of men, how long will you be dull of heart? why do you love vanity, and seek after lying? Know ye also that the Lord hath made his holy one wonderful: the Lord will hear me when I shall cry unto him. Be angry, and sin not: the things you say in your hearts, be sorry for them upon your beds. Offer up the sacrifice of justice, and trust in the Lord: many say, Who sheweth us good things? The light of thy countenance O Lord, is signed upon us: thou hast given gladness in my heart. By the fruit of their corn, their wine and oil, they are multiplied. In peace in the selfsame I will sleep, and I will rest:"
    },
    {
      "type": "psalm",
      "label": "Psalm 91",
      "ref": "Psalm 91 · 1–11",
      "antiphon": "He that dwelleth in the aid of the Most High shall abide under the protection of the God of heaven.",
      "text": "The praise of a canticle for David. He that dwelleth in the aid of the most High, shall abide under the protection of the God of Jacob. He shall say to the Lord: Thou art my protector, and my refuge: my God, in him will I trust. For he hath delivered me from the snare of the hunters: and from the sharp word. He will overshadow thee with his shoulders: and under his wings thou shalt trust. His truth shall compass thee with a shield: thou shalt not be afraid of the terror of the night. Of the arrow that flieth in the day, of the business that walketh about in the dark: of invasion, or of the noonday devil. A thousand shall fall at thy side, and ten thousand at thy right hand: but it shall not come nigh thee. But thou shalt consider with thy eyes: and shalt see the reward of the wicked. Because thou, O Lord, art my hope: thou hast made the most High thy refuge. There shall no evil come to thee: nor shall the scourge come near thy dwelling. For he hath given his angels charge over thee; to keep thee in all thy ways."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "1 Peter 5 · 8–9",
      "text": "Be sober and watch: because your adversary the devil, as a roaring lion, goeth about seeking whom he may devour: whom resist ye, strong in faith."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Into thy hands, O Lord, I commend my spirit."
    },
    {
      "type": "canticle",
      "label": "The Nunc Dimittis",
      "sub": "Canticle of Simeon",
      "ref": "Luke 2 · 29–32",
      "antiphon": "Protect us, Lord, as we stay awake; watch over us as we sleep, that awake we may keep watch with Christ, and asleep rest in his peace.",
      "text": "Now thou dost dismiss thy servant, O Lord, according to thy word in peace; Because my eyes have seen thy salvation, Which thou hast prepared before the face of all peoples: A light to the revelation of the Gentiles, and the glory of thy people Israel."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "Visit, we beseech thee, O Lord, this dwelling, and drive far from it all snares of the enemy; let thy holy angels dwell herein to preserve us in peace, and let thy blessing be upon us always. Through Christ our Lord. Amen."
    },
    {
      "type": "canticle",
      "label": "Antiphon to Our Lady",
      "sub": "Salve Regina",
      "text": "Hail, holy Queen, Mother of mercy, our life, our sweetness, and our hope. To thee do we cry, poor banished children of Eve; to thee do we send up our sighs, mourning and weeping in this valley of tears. Turn then, most gracious advocate, thine eyes of mercy toward us; and after this our exile, show unto us the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ]
};
