// AUTO-GENERATED by scripts/build-office.mjs — do not edit by hand.
// A prayable Liturgy of the Hours from public-domain texts (Douay–Rheims psalms
// and canticles + the traditional ordinary). Not the licensed ICEL psalter.

export type OfficePartType = "versicle" | "psalm" | "canticle" | "reading" | "responsory" | "prayer";

export interface OfficePart {
  type: OfficePartType;
  label?: string;
  sub?: string;
  ref?: string;
  antiphon?: string;
  text: string;
}

export const OFFICE: Record<string, OfficePart[]> = {
  "Lauds": [
    {
      "type": "versicle",
      "text": "O Lord, open thou my lips, and my mouth shall declare thy praise."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 63",
      "ref": "Psalm 63 · 1–8",
      "antiphon": "O God, my God, to thee do I watch at the break of day.",
      "text": "A psalm of David when he was in the desert of Edom. O God, my God, to thee do I watch at break of day. For thee my soul hath thirsted; for thee my flesh, O how many ways! In a desert land, and where there is no way, and no water: so in the sanctuary have I come before thee, to see thy power and thy glory. For thy mercy is better than lives: thee my lips shall praise. Thus will I bless thee all my life long: and in thy name I will lift up my hands. Let my soul be filled as with marrow and fatness: and my mouth shall praise thee with joyful lips. If I have remembered thee upon my bed, I will meditate on thee in the morning: because thou hast been my helper. And I will rejoice under the covert of thy wings:"
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "Romans 13 · 12",
      "text": "The night is passed, and the day is at hand. Let us therefore cast off the works of darkness, and put on the armour of light."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "I will bless the Lord at all times; his praise shall be ever in my mouth."
    },
    {
      "type": "canticle",
      "label": "The Benedictus",
      "sub": "Canticle of Zechariah",
      "ref": "Luke 1 · 68–79",
      "antiphon": "Blessed be the Lord, the God of Israel, for he hath visited and wrought the redemption of his people.",
      "text": "Blessed be the Lord God of Israel; because he hath visited and wrought the redemption of his people: And hath raised up an horn of salvation to us, in the house of David his servant: As he spoke by the mouth of his holy prophets, who are from the beginning: Salvation from our enemies, and from the hand of all that hate us: To perform mercy to our fathers, and to remember his holy testament, The oath, which he swore to Abraham our father, that he would grant to us, That being delivered from the hand of our enemies, we may serve him without fear, In holiness and justice before him, all our days. And thou, child, shalt be called the prophet of the Highest: for thou shalt go before the face of the Lord to prepare his ways: To give knowledge of salvation to his people, unto the remission of their sins: Through the bowels of the mercy of our God, in which the Orient from on high hath visited us: To enlighten them that sit in darkness, and in the shadow of death: to direct our feet into the way of peace."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "Almighty God, who hast brought us to the beginning of this day: defend us in the same by thy mighty power, that this day we may fall into no sin, but that all our doings may be ordered by thy governance, to do always that which is righteous in thy sight. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Terce": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 67",
      "ref": "Psalm 67 · 1–7",
      "antiphon": "May God have mercy on us, and bless us.",
      "text": "Unto the end, in, hymns, a psalm of a canticle for David. May God have mercy on us, and bless us: may he cause the light of his countenance to shine upon us, and may he have mercy on us. That we may know thy way upon earth: thy salvation in all nations. Let people confess to thee, O God: let all people give praise to thee. Let the nations be glad and rejoice: for thou judgest the people with justice, and directest the nations upon earth. Let the people, O God, confess to thee: let all the people give praise to thee: the earth hath yielded her fruit. May God, our God bless us,"
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "Acts 2 · 4",
      "text": "And they were all filled with the Holy Spirit, and they began to speak the wonderful works of God."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Come, Holy Spirit, fill the hearts of thy faithful, and kindle in them the fire of thy love."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O Lord, pour forth thy Spirit upon us at this third hour, as thou didst pour him upon the apostles in tongues of fire; that we, made fervent in thy love, may confess thee before all the world. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Sext": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 121",
      "ref": "Psalm 121 · 1–8",
      "antiphon": "My help is from the Lord, who made heaven and earth.",
      "text": "In my trouble I cried to the Lord: and he heard me. O Lord, deliver my soul from wicked lips, and a deceitful tongue. What shall be given to thee, or what shall be added to thee, to a deceitful tongue. The sharp arrows of the mighty, with coals that lay waste. Woe is me, that my sojourning is prolonged! I have dwelt with the inhabitants of cedar: my soul hath been long a sojourner. With them that hate peace I was peaceable: when I spoke to them they fought against me without cause."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "2 Corinthians 6 · 2",
      "text": "Behold, now is the acceptable time; behold, now is the day of salvation."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "The Lord is my light and my salvation; whom shall I fear?"
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O God, who at the sixth hour didst stretch out thine arms upon the Cross for the salvation of the world: kindle in us at this midday the fire of thy charity, that all our works may be pleasing unto thee. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "None": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 126",
      "ref": "Psalm 126 · 1–6",
      "antiphon": "They that sow in tears shall reap in joy.",
      "text": "They that trust in the Lord shall be as mount Sion: he shall not be moved for ever that dwelleth in Jerusalem. Mountains are round about it: so the Lord is round about his people from henceforth now and for ever. For the Lord will not leave the rod of sinners upon the lot of the just: that the just may not stretch forth their hands to iniquity. Do good, O Lord, to those that are good, and to the upright of heart. But such as turn aside into bonds, the Lord shall lead out with the workers of iniquity: peace upon Israel."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "Colossians 3 · 17",
      "text": "All whatsoever you do in word or in work, do all in the name of the Lord Jesus Christ, giving thanks to God and the Father by him."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "My soul yearns and pines for the courts of the Lord."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "O God, who at the ninth hour didst will that thy Son should taste death for us all: grant that, as the day declines, our hearts may turn ever more wholly unto thee, who livest and reignest, world without end. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Vespers": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 141",
      "ref": "Psalm 141 · 1–5",
      "antiphon": "Let my prayer be directed as incense in thy sight, O Lord.",
      "text": "Unto the end, a psalm for David. Deliver me, O Lord, from the evil man: rescue me from the unjust man. Who have devised iniquities in their hearts: all the day long they designed battles. They have sharpened their tongues like a serpent: the venom of saps is under their lips. Keep me, O Lord, from the hand of the wicked: and from unjust men deliver me. Who have proposed to supplant my steps."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "2 Corinthians 1 · 3–4",
      "text": "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort, who comforteth us in all our tribulation."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Let my prayer come like incense before thee, the lifting up of my hands like the evening sacrifice."
    },
    {
      "type": "canticle",
      "label": "The Magnificat",
      "sub": "Canticle of Mary",
      "ref": "Luke 1 · 46–55",
      "antiphon": "My soul doth magnify the Lord, and my spirit hath rejoiced in God my Saviour.",
      "text": "And Mary said: My soul doth magnify the Lord. And my spirit hath rejoiced in God my Saviour. Because he hath regarded the humility of his handmaid; for behold from henceforth all generations shall call me blessed. Because he that is mighty, hath done great things to me; and holy is his name. And his mercy is from generation unto generations, to them that fear him. He hath shewed might in his arm: he hath scattered the proud in the conceit of their heart. He hath put down the mighty from their seat, and hath exalted the humble. He hath filled the hungry with good things; and the rich he hath sent empty away. He hath received Israel his servant, being mindful of his mercy: As he spoke to our fathers, to Abraham and to his seed for ever."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "Lighten our darkness, we beseech thee, O Lord; and by thy great mercy defend us from all perils and dangers of this night. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ],
  "Compline": [
    {
      "type": "versicle",
      "text": "O God, come to my assistance. O Lord, make haste to help me."
    },
    {
      "type": "versicle",
      "text": "Glory be to the Father, and to the Son, and to the Holy Spirit: as it was in the beginning, is now, and ever shall be, world without end. Amen."
    },
    {
      "type": "psalm",
      "label": "Psalm 91",
      "ref": "Psalm 91 · 1–11",
      "antiphon": "He that dwelleth in the aid of the Most High shall abide under the protection of the God of heaven.",
      "text": "The praise of a canticle for David. He that dwelleth in the aid of the most High, shall abide under the protection of the God of Jacob. He shall say to the Lord: Thou art my protector, and my refuge: my God, in him will I trust. For he hath delivered me from the snare of the hunters: and from the sharp word. He will overshadow thee with his shoulders: and under his wings thou shalt trust. His truth shall compass thee with a shield: thou shalt not be afraid of the terror of the night. Of the arrow that flieth in the day, of the business that walketh about in the dark: of invasion, or of the noonday devil. A thousand shall fall at thy side, and ten thousand at thy right hand: but it shall not come nigh thee. But thou shalt consider with thy eyes: and shalt see the reward of the wicked. Because thou, O Lord, art my hope: thou hast made the most High thy refuge. There shall no evil come to thee: nor shall the scourge come near thy dwelling. For he hath given his angels charge over thee; to keep thee in all thy ways."
    },
    {
      "type": "reading",
      "label": "Reading",
      "ref": "1 Peter 5 · 8–9",
      "text": "Be sober and watch: because your adversary the devil, as a roaring lion, goeth about seeking whom he may devour: whom resist ye, strong in faith."
    },
    {
      "type": "responsory",
      "label": "Responsory",
      "text": "Into thy hands, O Lord, I commend my spirit."
    },
    {
      "type": "canticle",
      "label": "The Nunc Dimittis",
      "sub": "Canticle of Simeon",
      "ref": "Luke 2 · 29–32",
      "antiphon": "Protect us, Lord, as we stay awake; watch over us as we sleep, that awake we may keep watch with Christ, and asleep rest in his peace.",
      "text": "Now thou dost dismiss thy servant, O Lord, according to thy word in peace; Because my eyes have seen thy salvation, Which thou hast prepared before the face of all peoples: A light to the revelation of the Gentiles, and the glory of thy people Israel."
    },
    {
      "type": "prayer",
      "label": "Concluding Prayer",
      "text": "Visit, we beseech thee, O Lord, this dwelling, and drive far from it all snares of the enemy; let thy holy angels dwell herein to preserve us in peace, and let thy blessing be upon us always. Through Christ our Lord. Amen."
    },
    {
      "type": "versicle",
      "text": "Let us bless the Lord. Thanks be to God."
    }
  ]
};
